export const UPDATE_PERSONAL_DATA = 'personalData/UPDATE_PERSONAL_DATA';
export const CLEAR_PERSONAL_DATA = 'personalData/CLEAR_PERSONAL_DATA';
export const INITIALIZE_PERSONAL_DATA = 'personalData/INITIALIZE_PERSONAL_DATA';