export const IS_INITIALIZED = 'initialize/IS_INITIALIZED';
export const IS_FETCHING_INIT_DATA = 'initialize/IS_FETCHING_INIT_DATA';
export const NETWORK_CONNECTION_STATUS = 'initialize/NETWORK_CONNECTION_STATUS';
export const LOST_CONNECTION = 'initialize/LOST_CONNECTION';
export const SERVER_INACCESSIBLE = 'initialize/SERVER_INACCESSIBLE';